name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Gradle cache
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 🔑 Decode keystore dari secret
      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > app/corearsitek-key.jks

      # 🔧 Pastikan Gradle Wrapper ada (auto-fix kalau hilang)
      - name: Ensure Gradle Wrapper
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle Wrapper not found, generating..."
            gradle wrapper --gradle-version 8.4
          fi
          chmod +x ./gradlew

      # 🔨 Build Release APK
      - name: Build Release
        run: ./gradlew clean assembleRelease
        env:
          MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      # 📦 Upload artifact (APK)
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: CoreArsitekApp-Release
          path: app/build/outputs/apk/release/app-release.apk
