name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write   # biar bisa commit wrapper kalau perlu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # 🔧 Setup Gradle versi kompatibel dengan AGP
      - name: Set up Gradle 8.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      # 🔧 Pastikan wrapper lengkap (regenerate kalau kurang file .jar)
      - name: Ensure Gradle Wrapper Complete
        run: |
          rm -rf gradle/wrapper
          gradle wrapper --gradle-version 8.4

      # Optional: commit wrapper ke repo biar permanen
      - name: Commit Gradle Wrapper
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add gradlew gradlew.bat gradle/wrapper/
            git commit -m "Add complete Gradle Wrapper 8.4"
            git push
          fi

      # 🔑 Decode keystore dari secrets
      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > corearsitek-key.jks

      # 🚀 Build release APK
      - name: Build Release APK
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleRelease

      # 📦 Upload hasil build
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
