name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Pastikan Gradle 8.4 tersedia
      - name: Set up Gradle 8.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      # Generate wrapper kalau belum ada
      - name: Generate Wrapper (Gradle 8.4)
        run: |
          if [ ! -f "./gradlew" ]; then
            gradle wrapper --gradle-version 8.4
          fi

      # Commit wrapper ke repo (biar permanen)
      - name: Commit Gradle Wrapper
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add gradlew gradlew.bat gradle/wrapper/gradle-wrapper.properties
            git commit -m "Add Gradle Wrapper 8.4"
            git push
          fi

      # Decode keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > corearsitek-key.jks

      # Build APK release
      - name: Build Release APK
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleRelease

      # Upload hasil build
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
