name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # biar bisa auto commit gradlew wrapper

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- Gradle Wrapper auto-fix ----
      - name: Ensure Gradle Wrapper exists
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle Wrapper not found, generating..."
            gradle wrapper --gradle-version 8.4
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add gradlew gradlew.bat gradle/wrapper/
            git commit -m "Add Gradle Wrapper 8.4" || echo "No changes to commit"
            git push || echo "No changes to push"
          fi

      # ---- Setup JDK ----
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # ---- Decode Keystore dari Secret ----
      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > app/corearsitek-key.jks

      # ---- Build APK & AAB Release ----
      - name: Build Release
        run: ./gradlew clean assembleRelease bundleRelease

      # ---- Upload Artifact ----
      - name: Upload Release APK & AAB
        uses: actions/upload-artifact@v4
        with:
          name: CoreArsitekApp
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
