name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # 3. Decode keystore dari secrets
      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > corearsitek-key.jks

      # 4. Build project
      - name: Build Release APK
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew clean assembleRelease
          else
            gradle clean assembleRelease
          fi

      # 5. Upload artifact (APK/AAB)
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
