name: Generate Gradle Wrapper

on:
  workflow_dispatch:  # jalan manual dari GitHub Actions

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle 8.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Generate Wrapper
        run: |
          gradle wrapper --gradle-version 8.4

      - name: Commit and Push Wrapper
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradlew gradlew.bat gradle/wrapper/gradle-wrapper.properties
          git commit -m "Add Gradle Wrapper 8.4"
          git push
